feat: add deBridge validator and integration test [SUP-6429]
superform-xyz/superform-core pull request #492
Opened 2024-04-04 08:00 UTC by sujithsomraaj

2024-04-04 08:08 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +        if (deBridgeQuote.allowedCancelBeneficiarySrc.length > 0) revert();
I guess this needs to be allowed?

2024-04-24 10:31 UTC, 0xTimepunk commented on foundry.toml
> +memory_limit = 1000000000
Remove this

2024-04-24 10:34 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +        /// FIXME: check upstream if the srcChain in this context is the block.chainid
are these FIXME's old? What was the cast about?

debridge chain ids are equal to block.chainId?

2024-04-24 10:34 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +        /// @dev allows dst swaps by coupling hashflow with other bridges
Nit: unsure what this hashflow comment refers to

2024-04-24 10:35 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +            /// @dev if there is a dst swap then the interim token should be the quote of hashflow
Nit: should be debridge

2024-04-24 10:36 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +        revert Error.CANNOT_DECODE_FINAL_SWAP_OUTPUT_TOKEN();
I would use a more meaningful error message here - ONLY_SWAPS_DISALLOWED for eg

2024-04-24 10:37 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +    /// NOTE: check other parameters including: `givePatchAuthoritySrc`
Nit: should use @notice instead of note so that natspec picks it up

2024-04-24 10:37 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +    /// NOTE: we should only allow the `tradeXChainRFQT` identifier
Nit: should use @notice instead of note so that natspec picks it up

2024-04-24 10:39 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +    function parseCallData(bytes calldata callData) public pure returns (bytes calldata) {
Any specific reason this is public?

2024-04-24 10:40 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +        if (v.xChainQuote.givePatchAuthoritySrc != address(0) || v.xChainQuote.allowedCancelBeneficiarySrc.length > 0) {
I would split the `v.xChainQuote.allowedCancelBeneficiarySrc.length > 0` from here and give it a more meaningful error message, bc INVALID_SRC_DEBRIDGE_AUTHORITY doesn't seem to pertain to it?

2024-04-24 10:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +        /// FIXME: check if address(uint160(uint256(b))) could be true ??
why would we need to perform this check? maybe consider removing this

2024-05-01 09:10 UTC, gpersoon commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +    }
maybe also check `allowedTakerDst` ?

2024-05-01 09:12 UTC, gpersoon commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +    }
Maybe also check:
- givePatchAuthoritySrc
- allowedTakerDst
- takeAmount

2024-05-01 09:14 UTC, gpersoon commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +        /// @dev allows dst swaps by coupling hashflow with other bridges
is hashflow correct here?

2024-05-01 09:14 UTC, gpersoon commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +            /// @dev if there is a dst swap then the interim token should be the quote of hashflow
is hashflow correct here?

2024-05-01 09:14 UTC, gpersoon commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +        /// @dev 1. chain id calidation
calidation typo?

2024-05-01 09:14 UTC, gpersoon commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +        /// @dev 1. chain id calidation
calidation typo?

2024-05-01 09:21 UTC, gpersoon commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +        if (v.selector == ICrossChainForwarder.strictlySwapAndCall.selector) {
Function strictlySwapAndCall uses checks on before/after balances but doesn't have a nonreentrancy modifier
There is always a potential risk of abuse in this pattern, although I can't quickly find a real attack
https://vscode.blockscan.com/ethereum/0xe67534a9f24cc000f467eaa17f920bf63b87a2cd

2024-05-09 11:41 UTC, 0xTimepunk requested changes
Some questions to clarify and perhaps extra validations. We're almost there!

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +            if (hasDstSwap && (args_.liqDataInterimToken != _castToAddress(deBridgeQuote.takeTokenAddress))) {
Should we also check the takeTokenAddress is equal to the vault asset address in the case of no dstSwap?

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +    }
if we don't intent to allow the user (giver) to increase the amount on source I think we should set givePatchAuthoritySrc to address(0) -> validate with the Debridge team this is correct

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +            superRegistry.getAddressByChainId(keccak256("DEBRIDGE_AUTHORITY"), args_.dstChainId)
Should agree with @vikramarun and @subhasishgoswami who is the address that is going to be the DEBRIDGE_AUTHORITY

In my opinion this could be the CORE_REGISTRY_UPDATER as it performs similar functionality

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +    /// @dev make sure the OrderCreation.allowedCancelBeneficiarySrc and OrderCreation.givePatchAuthoritySrc is the user address on source
I think we should not allow the user to add more input tokens as that can affect the whole intent. Therefore I'd make sure that givePatchAuthoritySrc is address(0)

allowedCancelBeneficiarySrc I think should be validated to be the user address on source (to receive the tokens if any cancelation happens)

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +        if (permitEnvelope.length > 0) {
I assume this is validated to be 0 because tokens are in router and don't need spending ability (are approved in https://github.com/superform-xyz/superform-core/blob/dcc6c1d7b7f4d234b8400a6523ef668bdb977b7b/src/crosschain-liquidity/LiquidityHandler.sol#L50)

2024-05-09 11:41 UTC, 0xTimepunk commented on src/libraries/DeBridgeError.sol
> +library DeBridgeError {
I would move this file to 

crosschain-liquidity/debridge/errors and not the general libraries folder

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +    /// @notice check other parameters including: `givePatchAuthoritySrc`
just like in Debridgevalidator.sol comment. Perhaps more things need to be brought back to validateTxData function from the _decodeTxData internal function to achieve this:

> I think we should not allow the user to add more input tokens as that can affect the whole intent. Therefore I'd make sure that givePatchAuthoritySrc is address(0)
> 
> allowedCancelBeneficiarySrc I think should be validated to be the user address on source (to receive the tokens if any cancelation happens)

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +        if (deBridgeQuote.allowedCancelBeneficiarySrc.length > 0) revert();
Let's only allow cancelation by a keeper IMO

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +            superRegistry.getAddressByChainId(keccak256("DEBRIDGE_AUTHORITY"), args_.dstChainId)
Just like in debridgevalidator.sol comment 

> Should agree with @vikramarun and @subhasishgoswami who is the address that is going to be the DEBRIDGE_AUTHORITY
> 
> In my opinion this could be the CORE_REGISTRY_UPDATER as it performs similar functionality

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +    struct DecodedQuote {
I guess this was adapted from ICrossChainForwarder

I suggest to rename all inputs to what's present there in the arguments of strictlySwapAndCall and pass the descriptions of the args as comments to here too for clear understanding

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +            if (hasDstSwap && (args_.liqDataInterimToken != deBridgeQuote.outputToken)) {
Just like in DebridgeValidator.sol

> Should we also check the takeTokenAddress is equal to the vault asset address in the case of no dstSwap?

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +                ,
I think we should validate that _srcTokenInPermitEnvelope is 0

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +                ,
What is _srcSwapRouter used for? Can it be used against us? doesn't seem to be validated

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +                v.swapRefundAddress,
v.swapRefundAddress is extracted but not validated. I'd send back to the user so I'd validate against it, but check with @vikramarun

2024-05-09 11:41 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +        assembly {
any reason for using assembly here? This should be consistent with DebridgeValidator.sol

2024-05-09 11:41 UTC, 0xTimepunk commented on test/mocks/DeBridgeForwarderMock.sol
> +    function _parseCallDataMem(bytes memory data) internal pure returns (bytes memory calldata_) {
Should not use assembly if possible

2024-05-09 11:41 UTC, 0xTimepunk commented on test/unit/crosschain-liquidity/deBridge/DeBridgeValidator.t.sol
> +contract DeBridgeValidatorTest is ProtocolActions {
General comment: could we hardcode a real txData from din api and test it for both DebridgeValidator and Forwarder?

2024-05-09 11:41 UTC, 0xTimepunk commented on test/utils/TestTypes.sol
> +    address hashflowValidator;
Remove anything in the entire code related to hashflow

2024-05-10 08:00 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +        if (deBridgeQuote.allowedCancelBeneficiarySrc.length > 0) revert();
// An optional address on the source (current) chain where the given input tokens
        // would be transferred to in case order cancellation is initiated by the orderAuthorityAddressDst
        // on the destination chain. This property can be safely set to an empty bytes array (0x):
        // in this case, tokens would be transferred to the arbitrary address specified
        // by the orderAuthorityAddressDst upon order cancellation
        bytes allowedCancelBeneficiarySrc;

2024-05-10 08:02 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +            if (hasDstSwap && (args_.liqDataInterimToken != _castToAddress(deBridgeQuote.takeTokenAddress))) {
You're right, Closing this one

2024-05-10 08:02 UTC, 0xTimepunk commented on test/mocks/DeBridgeForwarderMock.sol
> +    function _parseCallDataMem(bytes memory data) internal pure returns (bytes memory calldata_) {
Let's use the same conditions as on source

2024-05-10 08:04 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +        assembly {
I see what you mean, probably not worth the effort. Let's leave it like this

2024-05-10 08:06 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +    /// @dev make sure the OrderCreation.allowedCancelBeneficiarySrc and OrderCreation.givePatchAuthoritySrc is the user address on source
We could use `receiverAddress` as that is present in ValidateTxDataArgs and make a note that if a user is using a contract wallet that is not create2 this won't work

(because receiverAddress is the address on destination, which for EOAs is the same but for contract accounts may not be)

2024-05-10 08:44 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +    }
To discuss with @vikramarun

2024-05-10 08:50 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +        if (v.selector == ICrossChainForwarder.strictlySwapAndCall.selector) {
I don't think this is a real risk for us in specific because there is the following validation 
![image](https://github.com/superform-xyz/superform-core/assets/45543880/21254baf-88d3-4d79-b168-705704a67f6b)

Also the user would be able to re-enter only in router functionality for which they would need to put up more tokens to deposit?

2024-05-10 08:52 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +    /// @dev make sure the OrderCreation.allowedCancelBeneficiarySrc and OrderCreation.givePatchAuthoritySrc is the user address on source
this is srcSender

2024-05-10 08:54 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +            if (deBridgeQuote.finalReceiver != args_.receiverAddress) revert Error.INVALID_TXDATA_RECEIVER();
Warning: receiverAddress is srcSender and this may be a contract that is not create2

2024-05-10 08:57 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +    /// @notice check other parameters including: `givePatchAuthoritySrc`
@sujithsomraaj validated allowedCancelBeneficiarySrc to be receiverAddress

wait for @vikramarun on givePatchAuthoritySrc

2024-05-10 09:48 UTC, subhasishgoswami commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +            superRegistry.getAddressByChainId(keccak256("DEBRIDGE_AUTHORITY"), args_.dstChainId)
Lets make it CORE_STATE_REGISTRY_RESCUER_ROLE, will be in line with whole rescue process

2024-05-13 10:03 UTC, gpersoon commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +        if (v.selector == ICrossChainForwarder.strictlySwapAndCall.selector) {
the routers are also whitelisted so there should be enough barriers

2024-05-13 11:26 UTC, 0xTimepunk commented on src/crosschain-liquidity/debridge/DeBridgeForwarderValidator.sol
> +                ,
Ask debridge to see if they have a registry of swapRouters, otherwise hard to maintain/validate

2024-05-13 22:08 UTC, vikramarun commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +    }
we could support this the same way we will have makePayment in activity page. 
but it should be the src sender user address

2024-05-13 22:09 UTC, vikramarun commented on src/crosschain-liquidity/debridge/DeBridgeValidator.sol
> +    /// @dev make sure the OrderCreation.allowedCancelBeneficiarySrc and OrderCreation.givePatchAuthoritySrc is the user address on source
we can support this the same way we would makePayment in activity page. let's include but have it be the src sender

2024-05-14 10:44 UTC, 0xTimepunk requested changes
A few more things to cleanup

2024-05-14 10:44 UTC, 0xTimepunk commented on script/forge-scripts/EnvironmentUtils.s.sol
> +            TARGET_CHAINS.push(FANTOM);
Remove fantom from here as it is not deployed into production

2024-05-14 10:44 UTC, 0xTimepunk commented on script/forge-scripts/misc/Abstract.Deploy.DeBridgeValidators.s.sol
> +        address expectedSr = env == 0
If this function is only going to be called by staging we don't need such if else

can be just 

```
address expectedSr = vars.chainId == 250 ? 0x7B8d68f90dAaC67C577936d3Ce451801864EF189 : 0xB2C097ac459aFAc892ae5b35f6bd6a9Dd3071F47;
```

2024-05-14 10:44 UTC, 0xTimepunk commented on script/utils/misc/run_script_mainnet_deBridge.sh
> +FOUNDRY_PROFILE=production forge script script/forge-scripts/misc/Mainnnet.DeployDeBridgeValidators.s.sol:MainnetDeployDeBridgeValidators --sig "deployDeBridgeValidator(uint256,uint256)" 0 7 --rpc-ur
Remove this fantom line, for now. Fantom is not on production

2024-05-14 10:44 UTC, 0xTimepunk commented on script/forge-scripts/Abstract.Deploy.Single.s.sol
> +    string[24] public contractNames = [
This file (Abstract.Deploy.Single.s.sol) needs to have the deployments of DebridgeValidator and debridge forwarderValidator (as it will be used when deploying fantom to production from here, for e.g)

2024-05-14 13:48 UTC, 0xTimepunk approved these changes
LGTM

2024-05-14 13:49 UTC, merged