feat: [SUP-6466] add axelar bridge + integration tests
superform-xyz/superform-core pull request #494
Opened 2024-04-04 09:34 UTC by sujithsomraaj

2024-04-17 13:30 UTC, 0xTimepunk requested changes
I few things to look at, but overall very good

2024-04-17 13:30 UTC, 0xTimepunk commented on src/crosschain-data/adapters/axelar/AxelarImplementation.sol
> +        if (address(gateway) == address(0)) {
If gateway != address(0) and gateway_ != address(0) the function is executed and nothing is emited. Instead, it should explicitly revert saying it only allows for 1 time config

2024-04-17 13:30 UTC, 0xTimepunk commented on src/crosschain-data/adapters/axelar/AxelarImplementation.sol
> +        // return gasEstimator.estimateGasFee(
I suppose this must not be hardcoded (are they live on gas estimates yet?)

2024-04-17 13:30 UTC, 0xTimepunk commented on src/crosschain-data/adapters/axelar/AxelarImplementation.sol
> +        if (processedMessages[msgId]) {
Does feel we should add this in other implementations when we perform an upgrade

2024-04-17 13:30 UTC, 0xTimepunk commented on src/crosschain-data/adapters/axelar/AxelarImplementation.sol
> +        /// NOTE: experimental split of registry contracts
What does this note refer to? Looks old

2024-04-17 13:30 UTC, 0xTimepunk commented on test/unit/crosschain-data/adapters/WormholeSRImplementation.t.sol
> +        ambId[0] = 6;
I'd use a large number here, otherwise when adding a new amb to the tests we're gonna hit this problem again

2024-04-17 13:30 UTC, 0xTimepunk commented on test/unit/super-registry/SuperRegistry.t.sol
> +        ambId[0] = 6;
Same here, see

2024-04-17 13:30 UTC, 0xTimepunk commented on test/unit/crosschain-data/adapters/WormholeSRImplementation.t.sol
> +            1, ISuperformFactory.PauseStatus.PAUSED, abi.encode(6, abi.encode(0, ""))
Same here, see

2024-04-17 13:30 UTC, 0xTimepunk commented on test/utils/BaseSetup.sol
> +    uint8[] public ambIds = [uint8(1), uint8(2), uint8(3), uint8(4), uint8(5)];
only the first id needs to be uint8(), all the others assume uint8 automatically

2024-04-18 12:49 UTC, 0xTimepunk reviewed
We should wait before sending this to v1 branch - gasEstimation not live yet

2024-04-20 07:59 UTC, gpersoon commented on src/vendor/axelar/StringAddressConversion.sol
> +        if (stringBytes.length != 42 || stringBytes[0] != "0" || stringBytes[1] != "x") revert();
could use custom error like
https://github.com/axelarnetwork/axelar-gmp-sdk-solidity/blob/main/contracts/libs/AddressString.sol

Same on line 34

2024-04-20 08:04 UTC, gpersoon commented on src/crosschain-data/adapters/axelar/AxelarImplementation.sol
> +        }
could probably also check `axelarChainId .length == 0`

2024-04-20 08:06 UTC, gpersoon commented on src/crosschain-data/adapters/axelar/AxelarImplementation.sol
> +        bytes memory /*extraData_ */
The function `generateExtraData()` above does generate `extraData`, shouldn't that be used?

2024-04-20 08:09 UTC, gpersoon commented on src/crosschain-data/adapters/axelar/AxelarImplementation.sol
> +        string memory axelerDstImpl = authorizedImpl[axelarChainId].toString();
Do check on `axelarChainId` (e.g. line 182/183) before line 180

Check `authorizedImpl[axelarChainId]` exists?

2024-04-20 08:24 UTC, gpersoon commented on src/crosschain-data/adapters/axelar/AxelarImplementation.sol
> +        if (superChainId[ambChainId_] == 0) {
could check `bytes(ambChainId_).length == 0` but maybe a bit overdone

2024-04-22 07:58 UTC, 0xTimepunk commented on src/vendor/axelar/StringAddressConversion.sol
> +        if (stringBytes.length != 42 || stringBytes[0] != "0" || stringBytes[1] != "x") revert();
Agree

2024-04-22 08:00 UTC, 0xTimepunk commented on src/crosschain-data/adapters/axelar/AxelarImplementation.sol
> +        }
Wouldn't hurt to check I guess

2024-04-22 10:48 UTC, 0xTimepunk reviewed
LGTM but let's wait on the gas estimation to re-test. let's park this for now

2024-04-22 10:56 UTC, gpersoon commented on src/crosschain-data/adapters/axelar/AxelarImplementation.sol
> +        }
oh I actually ment it could be replaced

2024-05-29 12:10 UTC, 0xTimepunk reviewed
Just a few things to look at and we're good to merge

2024-05-29 12:10 UTC, 0xTimepunk commented on script/forge-scripts/misc/Abstract.Deploy.Axelar.s.sol
> +    function _configureAxelar(
I assume this function is for staging, could prep a few if / elses here for prod where safe is used (without broadcasting)

2024-05-29 12:10 UTC, 0xTimepunk commented on script/utils/misc/run_script_mainnet_axelar.sh
> +FOUNDRY_PROFILE=production forge script script/forge-scripts/misc/Mainnet.DeployAxelar.s.sol:MainnetDeployAxelar --sig "deployAxelar( uint256,uint256, uint256)" 0 6 0 --rpc-url $BASE_RPC_URL --slow -
We're missing FTM here. Also for FTM it should use newSalt == 1 I think

2024-05-29 12:10 UTC, 0xTimepunk commented on script/utils/misc/run_script_mainnet_bridgeAdaptersV2.sh
> +echo Deploying bridge adapters: ...
Does this miss FTM also?

2024-05-29 12:10 UTC, 0xTimepunk commented on script/utils/verify_contracts.sh
> +    1
Why was FTM removed from mainnet verify_contracts?
Should restore the file to the original condition I guess

2024-05-29 12:10 UTC, 0xTimepunk commented on script/utils/verify_contracts_staging.sh
Same here, why was ftm removed?

2024-05-29 13:20 UTC, merged